new Vue({
  el:'.swiper-wrapper',
  data:function(){
    return{
      items:[
        {img:'img/banner1.jpg'},
        {img:'img/banner2.jpg'},
        {img:'img/banner3.jpg'},
        {img:'img/banner4.jpg'},
        {img:'img/banner5.jpg'},
        {img:'img/banner6.jpg'},
        {img:'img/banner7.jpg'},
        {img:'img/banner8.jpg'}
      ]
    }
  }
});
new Vue({
  el:'.bannerfl',
  data(){
    return{
      items:[
        {img:'img/bf1.dpg'},
        {img:'img/bf2.dpg'},
        {img:'img/bf3.dpg'}
      ]
    }
  }
});
new Vue({
  el:'.liebiao',
  data(){
    return{
      items:[
        {img:'img/sbanner1.webp'},
        {img:'img/sbanner2.webp'},
        {img:'img/sbanner3.webp'},
        {img:'img/sbanner4.webp'},
        {img:'img/sbanner5.webp'},
        {img:'img/sbanner6.webp'},
        {img:'img/sbanner7.webp'},
        {img:'img/sbanner8.webp'},
        {img:'img/sbanner9.webp'},
        {img:'img/sbanner10.webp'}
      ]
    }
  }
});
new Vue({
  el:'.jdkb',
  data(){
    return{
      items:[
        {x:'热门',y:'无限流量"是个坑，联通移动电信...'},
        {x:'hot',y:'小米8被吊打！荣耀反击太犀利...'},
        {x:'推荐',y:'麒麟980+魔法屏+40w快充，荣...'},
        {x:'最新',y:'鼻头里挤出小白粒...'}
      ]
    }
  }
});
new Vue({
  el:'.mrcj',
  data(){
    return{
      items:[
        {img:'img/mrcj1.jpg.dpg'},
        {img:'img/mrcj2.dpg'},
        {img:'img/mrcj3.dpg'}
      ]
    }
  }
});
new Vue({
  el:'.jdms',
  data(){
    return{
      items:[
        {x:'京东秒杀'},
        {x:'8点场'},
        {x:'更多秒杀'}
      ]
    }
  }
});
new Vue({
  el:'.jdmsmb',
  data(){
    return{
      items:[
        {img:'img/sj1.dpg',x:'￥3549',y:'￥3599'},
        {img:'img/cloth1.dpg',x:'￥99',y:'￥329'},
        {img:'img/ls1.dpg',x:'￥19.9',y:'￥48'},
        {img:'img/mm1.dpg',x:'￥29.9',y:'￥398'},
        {img:'img/jinqiu1.dpg',x:'￥3549',y:'￥3599'},
        {img:'img/sj2.dpg',x:'￥1999',y:'￥2299'},
        {img:'img/book1.dpg',x:'￥19.9',y:'￥50.4'},
        {img:'img/dudou1.dpg',x:'￥135',y:'￥193.2'},
        {img:'img/dfb1.dpg',x:'￥598',y:'￥699'},
        {img:'img/gq1.dpg',x:'￥3149',y:'￥3349'}
      ]
    }
  }
});
new Vue({
  el:'.paiban',
  data(){
    return{
      items:[
        {img:'img/shouye.png'},
        {img:'img/fenlei.png'},
        {img:'img/pingou.png'},
        {img:'img/gouwuche.png'},
        {img:'img/denglu.png'}
      ]
    }
  }
});
new Vue({
  el:'.bannerzq1',
  data(){
    return{
      items:[
        {img:'img/zqbbanner11.dpg'},
        {img:'img/zqbanner12.dpg'},
        {img:'img/zqbanner13.dpg'},
        {img:'img/zqbanner14.dpg'},
      ]
    }
  }
});
